service:
  name: ngskool-jacktator

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list


custom:
  tableName: 'NgSkool_Schools-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  stage: dev # Set the default stage used. Default is dev
  region: ap-southeast-2 # AWS Sydney Region
  runtime: nodejs10.x
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["SchoolsDynamoDBTable", "Arn" ] }
  environment:
    AWS_APP_REGION: ${self:provider.region}
    SCHOOLS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  createSchool:
    handler: index.handler
    events:
      - http: 'POST /schools'
#  getUser:
#    handler: index.handler
#    events:
#      - http: 'GET /users/{proxy+}'
#  hello:
#    handler: hello.hello
#    events:
#      - http:
#          method: get
#          path: hello

resources:
  Resources:
    SchoolsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: Id
            AttributeType: S
        KeySchema:
          -
            AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:custom.tableName}
