service:
  name: ngskool-jacktator

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2 # AWS Sydney Region

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
#  hello:
#    handler: handler.hello
#    events:
#      - http:
#          method: get
#          path: hello
