service:
  name: ngskool-jacktator

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: dev # Set the default stage used. Default is dev
  region: ap-southeast-2 # AWS Sydney Region
  runtime: nodejs10.x
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  hello:
    handler: hello.hello
    events:
      - http:
          method: get
          path: hello
