import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('NgSkool_Schools')
export class SKSchool {
    @autoGeneratedHashKey()
    id: string;

    @rangeKey({defaultProvider: () => new Date()})
    createdAt: Date;

    @attribute()
    name?: string;

    @attribute()
    address?: string;

    @attribute()
    numberOfStudents?: number;

    @attribute()
    completed?: boolean;

    @attribute({memberType: 'String'})
    tags?: Set<string>;
}
