/**
 * This is the Data Model for School object using dynamodb-data-mapper package
 *
 * @todo The 'Mapper' object is currently conflicting with serverless-local package. To be fixed in the future build.
 *
 * @see https://github.com/awslabs/dynamodb-data-mapper-js
 *
 * @author Jack
 * @since 1.0.0
 */
import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('NgSkool_Schools')
export class SKSchool {
    @autoGeneratedHashKey()
    id: string;

    @rangeKey({
        type: "Date",
        defaultProvider: () => new Date()
    })
    createdAt: Date;

    @attribute()
    name?: string;

    @attribute()
    address?: string;

    @attribute()
    numberOfStudents?: number;

    @attribute()
    completed?: boolean;

    @attribute({memberType: 'String'})
    tags?: Set<string>;
}
